main:
  push:
    - stages:
        - name: notify
          image: cnbcool/webhook
          settings:
            urls:
              - https://api.edgeone.ai/eo/pages/hook/cnb
            method: POST
            content_type: application/json
            template: |
              {
                "repoName": "{{ CNB_REPO_NAME }}",
                "repoUrl": "{{ CNB_REPO_URL_HTTPS }}",
                "branch": "{{ CNB_BRANCH }}",
                "commit": "{{ CNB_COMMIT_SHORT }}",
                "committer": "{{ CNB_COMMITTER }}",
                "event": "{{ CNB_EVENT }}",
                "buildId": "{{ CNB_BUILD_ID }}",
                "buildWebUrl": "{{ CNB_BUILD_WEB_URL }}",
                "buildUser": "{{ CNB_BUILD_USER }}",
                "pipelineName": "{{ CNB_PIPELINE_NAME }}"
              }
